server:
    port: 8080
    servlet:
        context-path: /identity

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/IdentityService"
        driverClassName: "org.postgresql.Driver"
        username: postgres
        password: 0843300042
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9094
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
jwt:
    signer-key: "xZr5iS8whFOkv0+DqsMTGTOJdlIWEMhsLS9x6OBTj/bK0GUsXRp0qTs/svpbfqz8"
    valid-duration: 720 #in seconds
    refreshable-duration: 7200 #in seconds

application:
    service:
        profile: http://localhost:8081/profile