server:
    port: 8888

app:
    api-prefix: api/v1

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            - id: organization_service
              uri: http://localhost:8081
              predicates:
              - Path=/${app.api-prefix}/organization/**
              filters:
              - StripPrefix=2
            - id: profile_service
              uri: http://localhost:8082
              predicates:
              - Path=/${app.api-prefix}/profile/**
              filters:
              - StripPrefix=2
            - id: classroom_service
              uri: http://localhost:8083
              predicates:
              - Path=/${app.api-prefix}/classroom/**
              filters:
              - StripPrefix=2