server:
    port: 8888

app:
    api-prefix: api/v1

spring:
    application:
        name: api-gateway
    main:
      web-application-type: reactive
    cloud:
        gateway:
            routes:
            - id: organization_service
              uri: http://${ORG_SERVICE_URL}:8081
              predicates:
              - Path=/${app.api-prefix}/organization/**
              filters:
              - StripPrefix=2
            - id: profile_service
              uri: http://${PROFILE_SERVICE_URL}:8082
              predicates:
              - Path=/${app.api-prefix}/profile/**
              filters:
              - StripPrefix=2
            - id: classroom_service
              uri: http://${CLASSROOM_SERVICE_URL}:8083
              predicates:
              - Path=/${app.api-prefix}/classroom/**
              filters:
              - StripPrefix=2
            - id: classevent_service
              uri: http://${CLASSEVENT_SERVICE_URL}:8084
              predicates:
              - Path=/${app.api-prefix}/classevent/**
              filters:
              - StripPrefix=2
            - id: post_service
              uri: http://${POST_SERVICE_URL}:8086
              predicates:
              - Path=/${app.api-prefix}/post/**
              filters:
              - StripPrefix=2
            - id: file_service
              uri: http://${FILE_SERVICE_URL}:8087
              predicates:
              - Path=/${app.api-prefix}/file/**
              filters:
              - StripPrefix=2

# eureka:
#     instance:
#         appname: api-gateway
#     client:
#         enabled: true
#         register-with-eureka: true
#         fetch-registry: true
#         service-url:
#             defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/v1/organization/v3/api-docs
        name: Organization Service
      - url: /api/v1/profile/v3/api-docs
        name: Profile Service
      - url: /api/v1/classroom/v3/api-docs
        name: Classroom Service
      - url: /api/v1/classevent/v3/api-docs
        name: ClassEvent Service
      - url: /api/v1/post/v3/api-docs
        name: Post Service