server:
  port: 8086
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/post-service?authSource=admin

app:
  services:
    profile:
      url: http://localhost:8081/profile
        
logging:
    level:
        org:
            springframework: 
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
                security: DEBUG
                data:
                    mongodb: DEBUG
                boot:
                    autoconfigure:
                        mongo: DEBUG

            hibernate:
                SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
        
        reactor:
            ipc:
                http:
                    server:
                        HttpServer: DEBUG
                    client: DEBUG

        io:
          reactivex:
            netty:
              protocol:
                http:
                  client: DEBUG
              handler:
                proxy:
                  HttpProxyHandler: DEBUG
                  ProxyHandler: DEBUG

openapi:
  service:
    title: grade-service doc
    version: 1.0.0
    url: http://localhost:8888 #api gateway url

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
    instance:
        appname: grade-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
