server:
    port: 8084
    servlet:
        contextPath: /classevent

spring:
    application: 
        name: classevent-service
    webflux:
        base-path: /classevent
    data:
        mongodb:
            # uri: mongodb://root:0843300042@localhost:27018/classeventdb?authSource=admin
            uri: mongodb://localhost:27017/classeventdb?authSource=admin
        
logging:
    level:
        org:
            springframework: 
                web:
                    filter:
                        reactive:
                            function:
                                client: DEBUG
                        CommonsRequestLoggingFilter: DEBUG
                security: DEBUG
                data:
                    mongodb: DEBUG
                boot:
                    autoconfigure:
                        mongo: DEBUG

            hibernate:
                SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
        
        reactor:
            ipc:
                netty:
                    channel:
                        ChannelOperationsHandler: DEBUG
                http:
                    server:
                        HttpServer: DEBUG
                    client: DEBUG

        io:
            reactivex:
                netty:
                    protocol:
                        http:
                            client: DEBUG
                    handler:
                        proxy:
                            HttpProxyHandler: DEBUG
                            ProxyHandler: DEBUG
  

eureka:
    instance:
        appname: classevent-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/


application:
    service:
        classroom: http://localhost:8083/classroom