server:
    port: 8084
    servlet:
        contextPath: /classevent

spring:
    application: 
        name: classevent-service
    webflux:
        base-path: /classevent
    data:
        mongodb:
            uri: mongodb://root:${MONGODB_PASSWORD:0843300042}@mongodb:27017/classeventdb?authSource=admin
        
logging:
    level:
        org:
            springframework: 
                security: DEBUG
            hibernate:
                SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
  
eureka:
    instance:
        appname: classevent-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/


application:
    service:
        classroom: http://${API_GATEWAY_URL}:/classroom