server:
  port: 9093
  
 
eureka:
  instance:
    appname: doc-service
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
      
swagger: 
  config: 
    refreshrate: 5000