server:
    port: 8088
    servlet:
        contextPath: /file

spring:
    webflux:
        base-path: /file
    application: 
        name: file-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/filedb?authSource=admin
        
logging:
    level:
        org:
            springframework: 
                security: DEBUG
            hibernate:
                SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
  
eureka:
    instance:
        appname: file-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

unicore:    
    openapi:
        dev-url: "http://localhost:8088/file"
        prod-url: "http://localhost:8088/file"