spring:
    application:
        name: file-service
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

google:
    oauth.callback.uri: http://${FILE_SERVICE_URL}.nip.io:8087/file/auth
    credentials.folder.path: ${GOOGLE_CREDENTIALS_PATH}