spring:
    application:
        name: file-service

google:
    secret.key.path: classpath:keys/client_secret_gd.json
    # oauth.callback.uri: http://192.168.1.106.nip.io/auth
    oauth.callback.uri: http://192.168.1.153.nip.io:8080/auth
    credentials.folder.path: file:D:\\Download
