server:
    port: 8083
    servlet:
        contextPath: /classroom

spring:
    webflux:
        base-path: /classroom
    application: 
        name: classroom-service
    data:
        mongodb:
            uri: mongodb://root:${MONGODB_PASSWORD:0843300042}@mongodb:27017/classroomdb?authSource=admin
        
logging:
    level:
        org:
            springframework: 
                security: DEBUG
            hibernate:
                SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
  
eureka:
    instance:
        appname: classroom-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

unicore:    
    openapi:
        dev-url: "http://localhost:8083/classroom"
        prod-url: "http://localhost:8083/classroom"

openapi:
  service:
    title: classroom-service doc
    version: 1.0.0
    url: http://${API_GATEWAY_URL} #api gateway url

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
    service:
        classevent: http://${API_GATEWAY_URL}/api/v1/classevent
        organization: http://${API_GATEWAY_URL}/api/v1/organization
        profile: http://${API_GATEWAY_URL}/api/v1/profile