server:
    port: 8083
    servlet:
        contextPath: /classroom

spring:
    webflux:
        base-path: /classroom
    application: 
        name: classroom-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/classroomdb?authSource=admin
        
logging:
    level:
        org:
            springframework: 
                security: DEBUG
            hibernate:
                SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
  
eureka:
    instance:
        appname: classroom-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

unicore:    
    openapi:
        dev-url: "http://localhost:8083/classroom"
        prod-url: "http://localhost:8083/classroom"