server:
    port: 8082
    servlet:
        contextPath: /profile

spring:
    webflux:
        base-path: /profile
    application: 
        name: profile-service
    r2dbc:
        url: r2dbc:pool:mysql://localhost:3306/${MYSQL_DB:profiledb}
        username: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:mysql}

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                orderInserts: true
                jdbc:
                    batchSize: 50
        show-sql: true
        # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    liquibase:
        url: jdbc:mysql://localhost:3306/${MYSQL_DB:profiledb}
        enabled: true
        user: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:mysql}
        change-log: classpath:db/changelog/changelog-master.xml
        
logging:
  level:
      org:
        springframework: 
            security: DEBUG
        hibernate:
            SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
  
eureka:
    instance:
        appname: profile-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

openapi:
  service:
    title: profile-service doc
    version: 1.0.0
    url: http://localhost:8888 #api gateway url

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

unicore:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080

application:
    service:
        classroom: http://localhost:8888/api/v1/classroom