server:
    port: 8081
    servlet:
        contextPath: /organization

spring:
    webflux:
        base-path: /organization
    application: 
        name: organization-service
    r2dbc:
        url: r2dbc:mysql://mysql:3306/${MYSQL_DB:organizationdb}
        username: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:mysql}
        pool:
            enabled: true
            max-size: 10
            initial-size: 5
            validation-query: SELECT 1

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                orderInserts: true
                jdbc:
                    batchSize: 50
        show-sql: true
        # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    liquibase:
        url: jdbc:mysql://mysql:3306/${MYSQL_DB:organizationdb}
        enabled: true
        user: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:mysql}
        change-log: classpath:db/changelog/changelog-master.xml
        
logging:
  level:
      org:
        springframework: 
            security: DEBUG
        hibernate:
            SQL: DEBUG
        com:
            netflix:
                eureka: OFF
                discovery: OFF
  
eureka:
    instance:
        appname: organization-service
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/


unicore:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080

profiles: Loc