server:
    port: 8080
    servlet:
        context-path: /organization

spring:
    application: 
        name: organization-service

    r2dbc:
        url: r2dbc:pool:mysql://localhost:3306/${MYSQL_DB:organizationdb}
        username: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:mysql}

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                orderInserts: true
                jdbc:
                    batchSize: 50

        show-sql: true
        # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    liquibase:
        url: jdbc:mysql://localhost:3306/${MYSQL_DB:organizationdb}
        enabled: true
        user: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:mysql}
        change-log: classpath:db/changelog/changelog-master.xml
        
logging:
    level:
        org:
            springframework: 
                security: DEBUG
            hibernate:
                SQL: DEBUG

        
